name: Markdown Lint

on:
  # This triggers the workflow when pushing or pulling changes to any branch
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run markdownlint on the specified files
      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            readme.md
            CONTRIBUTING.md
